# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98d0a43561be7c969397b3d9238d8ac4960f431636f4c4ad3e30cfb7c5b4e1b481062498266e5d8b6aba212f66cd78c84d5a8184e02d86a4900e6235a3250d10

test:
  secret_key_base: ead8493b15969150c6777aa4715a5857317dbea4a120a4d59e80b5264b7958ef5586957cf1056b4904092dd01f4cbdb45a7e6037facaeaa66167af08381aaad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
